kind: pipeline
name: default

steps:
- name: installing
  image: composer
  commands:
  - composer install

- name: testing
  image: php:7
  commands:
  - vendor/bin/phpunit --configuration config.xml
