---
kind: pipeline
type: ssh
name: default

server:
  host: seint-drone.digitalstacks.net
  user: ubuntu
  ssh_key:
    from_secret: ssh_key

steps:
- name: greeting
  commands:
  - echo hello world

...
