kind: pipeline
type: ssh
name: default

server:
  host: 35.72.31.70
  user: root
  password: virtualcom

platform: 
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world

...
