kind: pipeline
name: default

steps:
- name: build
  image: golang:1.12
  environment:
    CGO_ENABLED: "0"
  commands:
  - go test -v -cover ./...
  - go build

- name: publish
  image: plugins/docker
  settings:
    auto_tag: true
    repo: drone/registry-plugin
    password:
      from_secret: docker_password
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag
